### ISSUE TITLE
Default docker-compose example doesn't create DB

### ISSUE THREAD

**Issue by mattiasb** [pierrecdn/phpipam#51] opened 2019-05-03 14:34 UTC
The default `docker-compose` example doesn't seem to work.

I run this:
```shell
$ cat docker-compose.yml 
---
version: '2'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    restart: always
    volumes:
      - db_data:/var/lib/mysql
  ipam:
    depends_on:
      - mysql
    image: pierrecdn/phpipam
    environment:
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ENV_MYSQL_HOST=mysql
    ports:
      - "8088:80"
volumes:
  db_data:

$ docker-compose up
Starting ipam_mysql_1 ... done
Starting ipam_ipam_1  ... done
Attaching to ipam_mysql_1, ipam_ipam_1
ipam_1   | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.32.3. Set the 'ServerName' directive globally to suppress this message
ipam_1   | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.32.3. Set the 'ServerName' directive globally to suppress this message
ipam_1   | [Fri May 03 14:31:05.228124 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
ipam_1   | [Fri May 03 14:31:05.228182 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
mysql_1  | 2019-05-03 14:31:05 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1  | 2019-05-03 14:31:05 0 [Note] mysqld (mysqld 5.6.44) starting as process 1 ...
mysql_1  | 2019-05-03 14:31:05 1 [Note] Plugin 'FEDERATED' is disabled.
[ ... ]
```

Then I point my web browser to `localhost:8088` and get this:
![Screenshot from 2019-05-03 16-31-56](https://user-images.githubusercontent.com/1341313/57144276-03b7be80-6dc1-11e9-88ab-be15d41ec2ed.png)

I press `Working installation` and get this:
![Screenshot from 2019-05-03 16-32-02](https://user-images.githubusercontent.com/1341313/57144372-3b266b00-6dc1-11e9-969d-f7992da2d128.png)

**Comment by bcorner13** [comment] 2019-06-28 02:27
add `    MYSQL_ENV_MYSQL_HOST: mysql` to the ipam:environment section.

**Comment by mattiasb** [comment] 2019-06-28 02:42
> add ` MYSQL_ENV_MYSQL_HOST: mysql` to the ipam:environment section.

I think you read my post a bit too fast. It's there. :)

**Comment by netflo** [comment] 2019-07-16 12:19
note that the issue is with the database not being present BUT it is most likely caused by the (desirable) storage persistence in the docker-compose file itself (ref: db_data:/var/lib/mysql) .
If I am right then  it must have worked ok in the past and stopped working after a reploy or reboot or something like that.  Am I right and is it your own test environment or on your laptop? 
If not, make sure you have not tweaked the ticks under the "show advanced options" during the install

**Comment by pierrecdn** [comment] 2019-11-05 22:58
Hi,
Sorry for not being very late here.

My sample config worked at some point, but I'm not an active user of docker-compose, so this may have changed and I remember having bad feelings with all the changes that had been done with 3 / 3.1 config formats and their consequence regarding the networking setup in recent versions.

Anyway, is there still any issue for some of you or should I close this?

**Closed as completed** 2020-02-27 14:57 UTC
