### ISSUE TITLE
Discovery Crons

### ISSUE THREAD

**Issue by christianreiss** [pierrecdn/phpipam#31] opened 2018-09-27 19:40 UTC
Hey,

awesome, running was a breeze. How are the cron jobs (Alive Check/ Discovery Check) handled?
I might be mistaken, but I only seen apache processes in the container.

-Chris.

**Comment by infradump** [comment] 2018-10-03 03:28
Duplicate of #27

**Comment by pierrecdn** [comment] 2018-10-03 07:19
Thanks @infradump for answering.
TL;DR: use phpipam-agent.
@christianreiss I'm closing since it seems to me that it may answer your needs.
Feel free to reopen if not the case.

**Closed as completed by pierrecdn** 2018-10-03 07:19 UTC
